name: sufficient_goldfish
description: The fish shopping app you've been waiting for.

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: '^0.6.2'
  image_picker: '^0.4.1'
  device_info: '^0.2.0'
  audioplayer: '^0.4.0'
  path_provider: '^0.4.0'
  firebase_auth: '^0.5.5'
  firebase_storage: '^0.2.2'
  simple_coverflow: '^0.0.6'
  firebase_core: '^0.2.1'
  sensors: '^0.3.1'
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fish-silhouette.png
    - assets/background.mp3
    - assets/saved.mp3
  uses-material-design: true
